### ISSUE TITLE
Bug report for the network extraction of "big" Scopus corpus

### ISSUE THREAD

**Issue by tommv** [tommv/bibliograph#20]
The following report concerns the bugs generated while extracting a network from a corpus of 10 CSVs file downloaded from Scopus. The files can be found in this archive:
https://www.dropbox.com/s/4d6xu33ubkcxp8e/ScopusTestCorpus.zip?dl=0

The number of nodes for each type in the exported gexf do not correspond to the number selected in the filter screen. Specifically, these are the numbers:
![image](https://user-images.githubusercontent.com/4007062/98168282-a6875680-1eea-11eb-8040-00e80996b0af.png)

**Comment by paulgirard** [comment]
There were bugs which explain this.
But note that the number will not be the same as : 
- nodes with 0 degree are filtered
- we keep only the largest component
