### ISSUE TITLE
A weird set of references in scopus (2).csv

### ISSUE THREAD

**Issue by paulgirard** [tommv/bibliograph#21]
Some articles in scopus (2).csv makes a huge set of wrong refs. The size of the CSV is much higher than others too.
Something fishy.
The parsing might be wrong but the original data seems doubtful.
![image](https://user-images.githubusercontent.com/193478/98710776-66115800-2384-11eb-8fb5-bf5481458aba.png)

**Comment by tommv** [comment]
The huge set of wrong refs comes from three duplicated lines in the CSV file.
The much higher size of the CSV however does not seem to be a bug.

**Comment by paulgirard** [comment]
should be solved by #22
