### ISSUE TITLE
(MINOR) problems with pluralization in the filter screen

### ISSUE THREAD

**Issue by tommv** [tommv/bibliograph#24]
Two ss in the variable names in the filter screen
Also the affiliation institution line breaks because too long.

<img width="893" alt="Screenshot 2020-11-16 at 11 54 54" src="https://user-images.githubusercontent.com/4007062/99247313-15c44b00-2807-11eb-932d-207c5d57a749.png">

**Comment by paulgirard** [comment]
Corrected. For info, the label of the variable is set in CSVFormats.ts file
